### ISSUE TITLE
KPM - Slight Typo

### ISSUE THREAD

**Issue by gnattishness** [Ledger-Donjon/ledger-donjon.github.io#8]
Hi,
I think there might be a slight typo at https://github.com/Ledger-Donjon/ledger-donjon.github.io/blame/master/_posts/2021-07-06-kaspersky-password-manager.md#L114
Is this intended to be "the biggest multiple of 10 lower than 32"?

Thanks for the great write up!

**Comment by gnattishness** [comment]
Ah, and for the code-block just below, it should probably be:
` return charset[uGen%10];

**Comment by jibeee** [comment]
Thanks!

Sorry, I did not see your issue, and noticed the first you mentioned with this tweet: https://twitter.com/ericlaw/status/1412560651860512768, and fixed it in 2e84c2814c99f716c6fc432de22e2385eb0707c0.

The code-block below was indeed wrong. I used your fix here: ec2d72f4e7b098bab2f4e670db0e089ea2bd8cb6.
